### ISSUE TITLE
check the checkboxes based on the export values when have same names

### ISSUE THREAD

**Issue by satyajitnayk** [cantoo-scribe/pdf-lib#32]
### Describe your idea

- I have a [checkbox.pdf](https://github.com/cantoo-scribe/pdf-lib/files/12852742/checkbox.pdf) with two check box groups.
- check boxes in each group have same name but different export values.
- How can I check checkbox based on their export value?

### How could this be implemented?

- I am able to find the check box with the export value, but no idea how to check it using it's widget reference!!
```ts
      if (field instanceof PDFCheckBox) {
          const widgets = field.acroField.getWidgets();
          for (const widget of widgets) {
            const exportValue = widget
              .getOnValue()
              ?.['encodedName'].replace(/^\//, '');
            console.log(exportValue, ' ==> ', widget.getAppearanceState());
            if (exportValue == value) {
              // widget.setAppearances();
              // check the check box using widget => no functionality available  in pdf-lib as of now it seems
              break;
            }
          }
      }
```
- May be we need some method to check a checkbox using widget reference!

### What problem are you trying to solve?

check the checkboxes based on the export values when all checkbox have same name.

### Why does this matter to you?

- We have a product that helps customer to fill fillable pdfs. 

<img width="817" alt="image" src="https://github.com/cantoo-scribe/pdf-lib/assets/32722867/ee89f8c7-6a89-407d-8e2b-3694cb09b7ce">

- The requirement is customer wants to check checkbox 2 in first group & checkbox 1 in 2nd group. As all checkbox of first group have same names but different export values; same for 2nd group as well.

### Would others find this helpful?

- It's useful when filling a fillable pdf having checkbox group with same names & different export values.
- Others will also find it useful.

### Are you interested in implementing your proposal?

Yes

### Why are you submitting a proposal?

shared in `How could this be implemented?`

**Comment by Sharcoux** [comment]
Sounds like a good addition. Do you think that you could open a PR? I don't think that we have the resources to develop this now.

**Comment by sam-goodwin** [comment]
I have the same problem - check boxes acting like radio groups because of export name.

Here's a nice sample PDF that exhibits the changes well:
[RadioCheckBox_AcroForm.pdf](https://github.com/cantoo-scribe/pdf-lib/files/12862754/RadioCheckBox_AcroForm.pdf)

**Comment by sam-goodwin** [comment]
> Sounds like a good addition. Do you think that you could open a PR? I don't think that we have the resources to develop this now.

@Sharcoux can you point out some key sections in the code that need to be changed?

**Comment by sam-goodwin** [comment]
This seems relevant. 

https://github.com/cantoo-scribe/pdf-lib/blob/f57f239ff2c91c176bcbeb58dc4d473566decb23/src/core/acroform/PDFAcroCheckBox.ts#L22-L27

**Comment by Sharcoux** [comment]
src/api/form/PDFCheckBox.ts

I can't help much more, though. We just took over the maintenance of the repo and I only know a small subset of the code base.

**Comment by sam-goodwin** [comment]
I managed to set the value with the following hack:

Comment out the exception here: https://github.com/cantoo-scribe/pdf-lib/blob/master/src/core/acroform/PDFAcroCheckBox.ts#L24

```ts
if (value !== onValue && value !== PDFName_1.default.of('Off')) {
    // throw new errors_1.InvalidAcroFieldValueError();
}
```

Then, in my code:

```ts
if (field instanceof PDFCheckBox) {
  if (field.acroField.getWidgets().length > 1) {
    for (const widget of field.acroField.getWidgets()) {
      if (widget.getOnValue()!.decodeText() === value) {
        field.acroField.setValue(widget.getOnValue()!);
      }
    }
  }
```

This loops through until i find the widget with the onValue that matches the value i'm trying to set, in my case it's `"Opt3"`.

I then call `setValue` on the `acroField` and pass the widget's `onValue` which is of type `PDFName`.

Moving forward, should we allow `check` to accept an optional `PDFName` value to set and update this exception to account for CheckBoxes with multiple widgets?

**Comment by sam-goodwin** [comment]
Here's my patch that is working for my use-case:
```ts
PDFAcroCheckBox.prototype.setValue = function (value: PDFName) {
  const onValue = this.getOnValue() ?? PDFName.of("Yes");
  const allowedValues = this.getWidgets().map((w) => w.getOnValue());
  if (
    value !== onValue &&
    !allowedValues.includes(value) &&
    value !== PDFName.of("Off")
  ) {
    throw new InvalidAcroFieldValueError();
  }

  this.dict.set(PDFName.of("V"), value);

  const widgets = this.getWidgets();
  for (let idx = 0, len = widgets.length; idx < len; idx++) {
    const widget = widgets[idx];
    const state = widget.getOnValue() === value ? value : PDFName.of("Off");
    widget.setAppearanceState(state);
  }
};
```

I don't know enough about the PDF spec to know if my `allowedValues` here is safe. What are the possible states `getWidgets()` can be in?

**Comment by satyajitnayk** [comment]
> Here's my patch that is working for my use-case:
> 
> ```ts
> PDFAcroCheckBox.prototype.setValue = function (value: PDFName) {
>   const onValue = this.getOnValue() ?? PDFName.of("Yes");
>   const allowedValues = this.getWidgets().map((w) => w.getOnValue());
>   if (
>     value !== onValue &&
>     !allowedValues.includes(value) &&
>     value !== PDFName.of("Off")
>   ) {
>     throw new InvalidAcroFieldValueError();
>   }
> 
>   this.dict.set(PDFName.of("V"), value);
> 
>   const widgets = this.getWidgets();
>   for (let idx = 0, len = widgets.length; idx < len; idx++) {
>     const widget = widgets[idx];
>     const state = widget.getOnValue() === value ? value : PDFName.of("Off");
>     widget.setAppearanceState(state);
>   }
> };
> ```
> 
> I don't know enough about the PDF spec to know if my `allowedValues` here is safe. What are the possible states `getWidgets()` can be in?

This seems to working for me too. Hey if any one could advice on usage of `allowedValues`.
Other than that we need to test for multiple use cases & then we could create a PR @Sharcoux @sam-goodwin .
Good find though !👍🏻

**Comment by satyajitnayk** [comment]
Hey guys!! I found the working solution without any need for altering `setValue`. So we do not need any additional PR for this 🚀
```ts
   const value = "export value";
   if (field instanceof PDFCheckBox) {
        if (field.acroField.getWidgets().length > 1) {
          field.uncheck(); // to make sure any checkbox already checked is cleared
          for (const widget of field.acroField.getWidgets()) {
            const onValue = widget.getOnValue()!;
            if (onValue.decodeText() === value) {
              const state = onValue ?? PDFName.of('Off');
              widget.setAppearanceState(state);
            }
          }
        } else {
          if (value) {
            field.check();
          } else {
            field.uncheck();
          }
        }
    }
```

<img width="975" alt="image" src="https://github.com/cantoo-scribe/pdf-lib/assets/32722867/12ef0fc7-ee5c-4136-8b60-acf46829bf09">

<img width="1007" alt="image" src="https://github.com/cantoo-scribe/pdf-lib/assets/32722867/65b18289-f479-46a9-8bd4-f6ffcfb697da">

**Comment by sam-goodwin** [comment]
It's a nice workaround but I still think it's a gap in the abstraction. Might be worth keeping it open to discuss what it should look like from the high level api. 

I am also unblocked, which is great, but this will likely affect anyone else stumbling into this problem.

**Comment by satyajitnayk** [comment]
I think it’s a working solution , but if you think it still needed, we can re open the issue.

**Comment by Sharcoux** [comment]
Anyway, there is this thread now, of someone is looking for the same thing

**Comment by giox069** [comment]
Hi, it took me days before finding @satyajitnayk  hack. As proposed by @sam-goodwin, the correct place for this function is in the top level api, not in a closed issue.
There are still problem with this approach: if you flatten() the form after setting the checkbox, the checkbox disappear.

Another possible and maybe complete solution could be this never accepted PR on the original pdf-lib: https://github.com/Hopding/pdf-lib/pull/1685, but I never tested it.

I'm still investigating because I still need to set the value of a multivalue PDFCheckBox and then flatten() the form.
