### ISSUE TITLE
Error if Length entry is not present in encrypted PDF

### ISSUE THREAD

**Issue by githayu** [cantoo-scribe/pdf-lib#44]
### What were you trying to do?

`PDFDocument.load(pdfBytes, { password: '' })`

### How did you attempt to do it?

When attempting to load a PDF with a default password, an error occurs because the Length entry is unreadable.

### What actually happened?

@cantoo_pdf-lib.js?v=112218bc:20115 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'asNumber')
    at new CipherTransformFactory (@cantoo_pdf-lib.js?v=112218bc:20115:59)
    at _PDFDocument.load (@cantoo_pdf-lib.js?v=112218bc:20504:129)
    at async FileReader.<anonymous> (App.tsx:29:26)

### What did you expect to happen?

A value is set to keyLength.

https://github.com/cantoo-scribe/pdf-lib/blob/master/src/core/crypto.ts#L1549

### How can we reproduce the issue?

If the return value of `dict.get(PDFName.of('Length')` is undefined

https://github.com/cantoo-scribe/pdf-lib/blob/master/src/core/crypto.ts#L1548C22-L1548C51

### Version

1.20.2

### What environment are you running pdf-lib in?

Browser

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

### Additional Notes

The case where the return value of `dict.get(PDFName.of('Length')` is undefind should be considered.

**Comment by Sharcoux** [comment]
Released in 1.20.3
