### ISSUE TITLE
drawSvgPath results in upside-down drawing

### ISSUE THREAD

**Issue by bcholmes** [cantoo-scribe/pdf-lib#49]
### What were you trying to do?

I've been using the standard implementation of pdf-lib, but because it's basically abandonware, now, I tried to use the Cantoo version as a drop-in replacement.

It all worked well, but the only issue I encountered relates to a line drawing that I included on the PDF using the drawSvgPath method. With the standard pdf-lib, the path has the same orientation as the SVG drawing I extracted the path information from. With the Cantoo pdf-lib, the drawing is upside-down.

### How did you attempt to do it?

Here's the code snippet I use. As I said, above, I'm trying to use it as a drop-in replacement for pdf-lib.

       drawOutline(pdf: PDFDocument, outline: string, options: SheetOutlineOptions) {
        const page = pdf.getPage(0);
        const scale =  PIXELS_TO_POINTS_RATIO * options.outlineScale;
        page.moveTo(options.outlineLocation.x, page.getHeight() - options.outlineLocation.y);
        page.drawSvgPath(outline, { borderColor: options.outlineColor,
            borderWidth: options.borderWidth / options.outlineScale,
            scale: scale })
    }

I also tried using the matrix transform option in the SvgOptions to apply a flip operation, but that didn't seem to change the output.

### What actually happened?

The outline appears upside-down (compared to the original SVG path), and renders above the y-axis (overlapping some PDF form elements).

### What did you expect to happen?

The outline to appear in the same orientation as the original SVG diagram.

### How can we reproduce the issue?

The main README for the project includes a code sample in [JSFiddle](https://jsfiddle.net/Hopding/bwaomr9h/2/). If run that code sample, you get one result. 

If you update the code sample to use the Cantoo version (changing the script reference to https://unpkg.com/@cantoo/pdf-lib@1.20.4) and download the resulting PDF, the lines are upside-down compared to the initial result.

### Version

1.20.4

### What environment are you running pdf-lib in?

Browser

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

### Additional Notes

I'm pretty sure that this has something to do with the coordinate space of PDFs being the opposite of SVG (the origin of PDFs is in the lower left corner; SVG is in the upper left). My guess is that the additional SVG support available in the Cantoo version is having a side-effect, here.

**Comment by bcholmes** [comment]
I'm assuming that the JSFiddle reference satisfies the need for the short, self-contained example.

**Comment by Sharcoux** [comment]
I see nothing upside down

![image](https://github.com/cantoo-scribe/pdf-lib/assets/797545/8fd79955-fc09-4f36-a89c-51567a33a2c6)

![image](https://github.com/cantoo-scribe/pdf-lib/assets/797545/2a0c9427-995c-4151-89c4-c13a9afcfc74)

**Comment by bcholmes** [comment]
Here is the screenshot of the original document:

<img width="901" alt="Screenshot 2024-03-04 at 9 58 14 AM" src="https://github.com/cantoo-scribe/pdf-lib/assets/2981347/cebc38d6-66dc-45d5-a604-9635081cd351">


And here's the document created with the Cantoo version:

<img width="902" alt="Screenshot 2024-03-04 at 9 57 28 AM" src="https://github.com/cantoo-scribe/pdf-lib/assets/2981347/73ea31ff-73a5-4e55-a954-9ee24e7b3035">

(I wondered, for a moment, if this was a problem specific to Mac Preview, but I see the same upsidedown-ness in Acrobat).

**Comment by Sharcoux** [comment]
Indeed. There is a problem when directly using drawSvgPath. We'll fix. Thanks.

**Comment by Sharcoux** [comment]
Solution released in v1.21.0

**Comment by bcholmes** [comment]
That was fast! Thank you so much!

**Comment by bcholmes** [comment]
For what it's worth, I've tested out this fix, and am using this version in my app now.
