### ISSUE TITLE
form.flatten() leaves border around checkboxes and radio groups

### ISSUE THREAD

**Issue by Nerdsie** [cantoo-scribe/pdf-lib#51]
### What were you trying to do?

Flatten a pdf containing fields such as checkboxes and radio groups

### How did you attempt to do it?

form.flatten();

### What actually happened?

![Screenshot 2024-03-09 045227](https://github.com/cantoo-scribe/pdf-lib/assets/1341449/baea3342-969b-4508-b732-24e41d295ea4)
![Screenshot 2024-03-09 050340](https://github.com/cantoo-scribe/pdf-lib/assets/1341449/763c8a14-79e2-49e0-8a63-63243d58660b)

After form.flatten() all checkboxes and radiogroups, whether they were selected or not, appear to have a border around where the previous form fields was.

### What did you expect to happen?

![image](https://github.com/cantoo-scribe/pdf-lib/assets/1341449/7a72e8c0-3ba2-4351-a2b6-2916d43ffae8)

The field should contain the proper value, but not have any erroneous borders added

### How can we reproduce the issue?

Attempt to .flatten() any pdf with checkboxes or radiogroups. 

### Version

1.21.0

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by Sharcoux** [comment]
Seems related to https://github.com/cantoo-scribe/pdf-lib/issues/41

We don't use that feature. If someone would like to have a look and suggest a PR, we might consider it.

**Comment by Sharcoux** [comment]
Solved with https://github.com/cantoo-scribe/pdf-lib/pull/56
