### ISSUE TITLE
Strange MediaBox and CropBox of PDF page

### ISSUE THREAD

**Issue by pedromdev** [cantoo-scribe/pdf-lib#59]
### What were you trying to do?

I'm trying to get the page boxes information to centralize an image.

### How did you attempt to do it?

I tried to get information from `getMediaBox()` or `getCropBox()` methods from `PDFPage` object to calculate the page center position.

### What actually happened?

I got strange informations about the page boxes. In some cases, height and width of a page is a negative value.

### What did you expect to happen?

Get the correct information about the page boxes.

### How can we reproduce the issue?

I added a [comment](https://github.com/Hopding/pdf-lib/issues/818#issuecomment-2258533632) in an old issue about the MediaBox and CropBox. I added the PDF that I tested and a piece of code.

> I have a PDF whose first page has different box information than the pages. However, when I retrieve this information using pdfinfo, I get information that differs from the information that pdf-lib gives me.
> 
> ![image](https://private-user-images.githubusercontent.com/4057098/353463518-fc10c285-d827-4064-a448-6c92684d2ae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjMzNTYsIm5iZiI6MTcyMjYyMzA1NiwicGF0aCI6Ii80MDU3MDk4LzM1MzQ2MzUxOC1mYzEwYzI4NS1kODI3LTQwNjQtYTQ0OC02YzkyNjg0ZDJhZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTgyNDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTYzZDg2NjdmNGY5ZDYxOTE5ZDZhMDczNmNhNmIzOThhN2I3YTJkMjc5MDAxZjExZGE4ZTY3NWNhZTEzMmYzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.q_5yvG2UNkpIvEY6V-0hHwOWd2POZ9B75KaV8nSeXwA) ![image](https://private-user-images.githubusercontent.com/4057098/353465165-11973a3b-6827-4061-ab37-bc80161194e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjMzNTYsIm5iZiI6MTcyMjYyMzA1NiwicGF0aCI6Ii80MDU3MDk4LzM1MzQ2NTE2NS0xMTk3M2EzYi02ODI3LTQwNjEtYWIzNy1iYzgwMTYxMTk0ZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTgyNDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmYyOGJhODk4ODFjOGE1YTcwMWQyNWJjZWJiOTY5OTFmZDNiNWE3YWE3NWU5ZDJmZDFiODE0YTUyNDIzYjQ0MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fngHjdwSJFPijrynKq3nw3dJlKdlVZ3aZBrJMRQSPSA) ![image](https://private-user-images.githubusercontent.com/4057098/353465515-da9feaa3-6d73-4835-96ba-19aeb9bc7409.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjMzNTYsIm5iZiI6MTcyMjYyMzA1NiwicGF0aCI6Ii80MDU3MDk4LzM1MzQ2NTUxNS1kYTlmZWFhMy02ZDczLTQ4MzUtOTZiYS0xOWFlYjliYzc0MDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTgyNDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzg0NWZhMmQwOGQ4NGQwYjQwMDA2OWQ0OTNkNGVkNTUxZWVmYmE1NjRhM2YyZDVjMmYxYWUxZmMzMmE2MmMwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7h0DkcC3qCA4K7MOkP0h-Xz6IBfFn-fhc2RRxuYa624) ![image](https://private-user-images.githubusercontent.com/4057098/353465409-823d2cba-b7e6-4409-b66a-7500960b22de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjMzNTYsIm5iZiI6MTcyMjYyMzA1NiwicGF0aCI6Ii80MDU3MDk4LzM1MzQ2NTQwOS04MjNkMmNiYS1iN2U2LTQ0MDktYjY2YS03NTAwOTYwYjIyZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTgyNDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzNmZWMwYWFlMjA0OWY1YzlmMTc1MzViOTgyNjk5ODVhMjYwNDFjYzg1NGUyYWFlMjJhYWE1OGYzNzdkNmFjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qefu-Lf3yTHSj4S7mMs52zgePTmlFjD6lxKIrcWXBt4)
> 
> I drew some circles using the CropBox information and this is how the 2 tests turned out. The first printout was using the pdfinfo information. The second printout was using the information that pdf-lib gives me through the getCropBox() method.
> 
> ![image](https://private-user-images.githubusercontent.com/4057098/353463795-135a7af5-d319-4788-996b-38b0efd8a135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjMzNTYsIm5iZiI6MTcyMjYyMzA1NiwicGF0aCI6Ii80MDU3MDk4LzM1MzQ2Mzc5NS0xMzVhN2FmNS1kMzE5LTQ3ODgtOTk2Yi0zOGIwZWZkOGExMzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTgyNDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzdkM2RiMDY5YjU3YjVhMzYwZWEzYzc1YzllNzM2YzBiZGIxY2IzNGExODMxOTZiZTM0MTQyMDM3ZGI2ODhmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GKU_EB6jxNUz7lNXlBuaaHc3MfMofc8gCwB1lt2-Cys) ![image](https://private-user-images.githubusercontent.com/4057098/353469910-cc262126-9f57-4cec-a967-b393232b9bea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjMzNTYsIm5iZiI6MTcyMjYyMzA1NiwicGF0aCI6Ii80MDU3MDk4LzM1MzQ2OTkxMC1jYzI2MjEyNi05ZjU3LTRjZWMtYTk2Ny1iMzkzMjMyYjliZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTgyNDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzk0ZDQ1Yjk3ZWVmYzgyZjY4NDU3NjU1NDY3N2E2MzlkMTI1M2VhM2JkY2U1ZDU0Nzk3ZWE4YzY2YmY4MTYwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QOG-tFFMdJTX93SCuMQSEX__T7tmb4vMSP75jM5jcc0) ![image](https://private-user-images.githubusercontent.com/4057098/353470051-9018a097-b252-43e6-9566-25f10c94407f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MjMzNTYsIm5iZiI6MTcyMjYyMzA1NiwicGF0aCI6Ii80MDU3MDk4LzM1MzQ3MDA1MS05MDE4YTA5Ny1iMjUyLTQzZTYtOTU2Ni0yNWYxMGM5NDQwN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTgyNDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc1OWUzODZlZTVmMzg4ODFlY2MwODRiNjIwYzFhZDMwMjE5NDg4MDU1ODBjNWJjMDJiOGVmMWI1MzgxNmM4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PLzZF3wmSl4UJB5oH8sMDpQe4KP747YQiQ16xwjN65k)
> 
> How is this MediaBox and CropBox information obtained in pdf-lib?
> 
> The example PDF is below:
> 
> [input2.pdf](https://github.com/user-attachments/files/16428520/input2.pdf)

**Note:** I understood later that height and width are used to calculate `xEnd` and `yEnd` of PDF page, but even if I calculate the end point I don't get the same information.

### Version

2.2.0

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

### Additional Notes

I did test in both versions and I got the same results:
- `pdf-lib`: 1.17.1
- `@cantoo/pdf-lib`: 2.2.0

**Comment by Sharcoux** [comment]
The pdf seems malformed, but we can update pdf-lib to handle this malformation. How did this pdf get generated?

**Comment by Sharcoux** [comment]
Solved in @cantoo/pdf-lib: 2.2.0

**Comment by pedromdev** [comment]
Hi @Sharcoux.

The PDF I added here is a partial PDF that I created from from another just for reproduce the behavior. According to `pdfinfo`, the original PDF was created in Adobe InDesign CS6.

![image](https://github.com/user-attachments/assets/62e8993e-fd2c-4462-93fc-c14f4afd5105)

**Comment by Sharcoux** [comment]
According to the specs,

```
The MediaBox is defined as an array of four numbers, typically in the format [llx lly urx ury], where:

    llx: The lower-left x-coordinate.
    lly: The lower-left y-coordinate.
    urx: The upper-right x-coordinate.
    ury: The upper-right y-coordinate.
```

In your provided pdf, the mediabox inverted the 2 y coordinates, leading to the wrong result. So, I don't know who is the culprit during the file generation, but the file is definitely malformed.

**Comment by RippleRurigaki** [comment]
I have seen this issue and have looked into it.

PDF specs,
Looking, 7.7.3.3 Page Object
> MediaBox type is "rectangle"


Looking, 7.9.5 Rectangles
> Rectangles are used to describe locations on a page and bounding boxes for a variety of objects.
> A rectangleshall be written as an array of four numbers giving the coordinates of a pair of diagonally opposite corners.
> 
> 
> NOTE Although rectangles are conventionally specified by their lower-left and upper-right corners,
> it is acceptable to specify any two diagonally opposite corners. 


I understand that it does not have to be [lower left, upper right], although that is not common.

I thought it would be easy to modify the values obtained,
 but I am concerned that it will not affect the other placement coordinates.

I have noticed this but have not been able to confirm it yet.
At this time I do not have the time.

**Comment by Sharcoux** [comment]
Ok. Well, anyway, from version 2.2.1, both will be supported, so I think I'll just close this. Thanks for the clarification.
